config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  scope module: :public do
    root to: 'homes#top'
    get "/about"=>"homes#about"
    resources :products, only: [:index, :show]
    resource :customers,only: [] do
      get "my_page"=>"customers#show"
      get "information/edit"=>"customers#edit"
      patch "information"=>"customers#update"
      get "unsubscribe"=>"customers#unsubscribe"
      patch "withdraw"=>"customers#withdraw"
    end

    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete "all_destroy"=>"cart_items#all_destroy"
      end
    end

    resources :orders, only: [:new, :create, :index, :show] do
          collection do
            post "confirm"=>"orders#confirm"
            get "complete"=>"orders#complete"
          end
        end
        resources :delivery_addresses, except: [:new, :show]
      end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
      root to: "homes#top"
      resources :products, except: [:destroy]
      resources :genres, only: [:index, :create, :edit, :update]
      resources :customers, only: [:index, :show, :edit, :update]
      resources :orders, only: [:show, :update] do
        resources :order_details, only: [:update]
      end
    end

  get 'searches/search', to: 'searches#search'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :product
    
    def subtotal
    product.with_tax_price * quantity
    end
    
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    # with_options presence: true do
    #   validates :last_name
    #   validates :first_name
    #   validates :last_name_kana
    #   validates :first_name_kana
    #   validates :email
    #   validates :postal_code
    #   validates :address
    #   validates :telephone_number
    # end

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :delivery_addresses, dependent: :destroy
  
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
  
end

app/models/delivery_address.rb
class DeliveryAddress < ApplicationRecord
    belongs_to :customer



  # private

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + addressee
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
    #t.string :name, null: false
    has_many :products, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
    enum payment_method: { credit_card: 0, transfer: 1 }
    enum order_status: { waiting_for_payment: 0, payment_confirmation: 1, now_at_work: 2, shipping_preparation: 3, sent: 4 }
    belongs_to :customer
    has_many :order_details, dependent: :destroy
    has_many :products ,through: :order_details

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum making_status: { cannot_start: 0, wait_for_production: 1, work_in_progress: 2, production_completed: 3}
    belongs_to :order
    belongs_to :product

    validates :quantity, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :genre

    has_many :carts, dependent: :destroy
    has_many :order_details, dependent: :destroy
    has_many :orders, through: :order_details

    has_one_attached :image

    def with_tax_price
    tax = 1.1
    (tax_excluded_price * tax).floor
    end

    # validation
     validates :name, presence: true
     validates :description, presence: true
     validates :tax_excluded_price,  presence: true

end

app/models/search.rb
class Search < ApplicationRecord
   def self.search(search)
      return Product.all unless search
      Product.where(['content LIKE ?', "%#{search}%"])
    end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page]).per(10)
  end
  
  def show
    @customer = Customer.find(params[:id])
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
     if @customer.update(customer_params)
        redirect_to admin_customer_path(@customer.id)
     else
        render :edit, notice: "変更に失敗しました"
     end
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:is_deleted, :email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render 'index'
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path(@genre.id)
    else
      render "edit"
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_admin!, if: -> { request.path =~ /^\/admin/ }
    before_action :authenticate_customer!, if: -> { request.path =~ /^\/customer/ || request.path =~ /^\/cart_items/ || request.path =~ /^\/orders/ || request.path =~ /^\/delivery_addresses/ }

  private
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    #Viewのformで取得したパラメータをモデルに渡す
    @products = Product.search(params[:search])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/serches_helper.rb
module SerchesHelper
end

app/views/admin/customers/edit.html.erb
<div class='container mt-5'>
  <div class='row'>
    <h3 class="page-name">
      <strong>
        <%= @customer.last_name %><%= @customer.first_name %>
        さんの会員情報編集
      </strong>
    </h3>
  </div></br>
  
  <%= form_with model: [:admin, @customer] do |f| %>
  <div class="row">
    <div class="col">
      
      <div class="row">
        <div class="col-3">
          <p>会員ID</p>
        </div>
        <div class="col-9">
          <%= @customer.id %>
        </div>
      </div>
      
      <div class="row">
        <div class="col-3">
          <p>氏名</p>
        </div>
        <div class="col-9">
          <%= f.text_field :last_name %>&nbsp;<%= f.text_field :first_name %>
        </div>
      </div>

      <div class="row">
        <div class="col-3">
          <p>フリガナ</p>
        </div>
        <div class="col-9">
          <%= f.text_field :last_name_kana %>&nbsp;<%= f.text_field :first_name_kana %>
        </div>
      </div>
      
      <div class="row">
        <div class="col-3">
          <p>郵便番号</p>
        </div>
        <div class="col-9">
          <%= f.text_field :postal_code %>
        </div>
      </div>
      
      <div class="row">
        <div class="col-3">
          <p>住所</p>
        </div>
        <div class="col-9">
          <%= f.text_field :address %>
        </div>
      </div>
      
      <div class="row">
        <div class="col-3">
          <p>電話番号</p>
        </div>
        <div class="col-9">
          <%= f.text_field :telephone_number %>
        </div>
      </div>
      
      <div class="row">
        <div class="col-3">
          <p>メールアドレス</p>
        </div>
        <div class="col-9">
          <%= f.text_field :email %>
        </div>
      </div>
      
      <div class="row">
        <div class="col-3">
          <p>会員ステータス</p>
        </div>
        <div class="col-9">
          <%= f.radio_button(:is_deleted, false) %><%= f.label :is_deleted_in_use, '有効' %>&nbsp;
          <%= f.radio_button(:is_deleted, true) %><%= f.label :is_deleted_withdrawal, '退会' %>
        </div>
      </div>

    </div>
  </div>
  
  <div class="container text-center mt-4">
      <div class="col-xs-offset-1">
        <%= f.submit "変更を保存する" ,class: 'btn btn-outline-success' %>
      </div>
  </div>
  <% end %>
  
</div>

app/views/admin/customers/index.html.erb
<%= render :layout => '/admin/shared/section_layout', :locals => {:title => '会員一覧'} do %>
  <table class="table">
    <thead class="thead-lignt bg-light">
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
        <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer.id) %></td>
          <td><%= customer.email %></td><!--メアド-->
          <td><!--有効、退会ステータス-->
              <% if customer.is_deleted === false %>
                <strong class="text-success">有効</strong>
              <% else %>
                退会
              <% end %>
          </td>
        </tr>
        <% end %>
    </tbody>
  </table>
  <div class="mt-5">
    <%= paginate @customers, theme: 'twitter-bootstrap-4'  %>
  </div>
<% end %>

app/views/admin/customers/show.html.erb
<div class='container mt-5'>
  <div class='row'>
    <h3 class="page-name">
      <strong>
        <%= @customer.last_name %><%= @customer.first_name %>
        さんの会員詳細
      </strong>
    </h3>
  </div></br>

    <div class="row">
      <div class="col">
        
        <div class="row">
          <div class="col-3">
            <p>会員ID</p>
          </div>
          <div class="col-9">
            <%= @customer.id %>
          </div>
        </div>
          
        <div class="row">
          <div class="col-3">
            <p>氏名</p>
          </div>
          <div class="col-9">
            <%= @customer.last_name + @customer.first_name %>
          </div>
        </div>
          
        <div class="row">
          <div class="col-3">
            <p>フリガナ</p>
          </div>
          <div class="col-9">
            <%= @customer.last_name_kana + @customer.first_name_kana %>
          </div>
        </div>
  
        <div class="row">
          <div class="col-3">
            <p>郵便番号</p>
          </div>
          <div class="col-9">
            <%= @customer.postal_code %>
          </div>
        </div>
        
        <div class="row">
          <div class="col-3">
            <p>住所</p>
          </div>
          <div class="col-9">
            <%= @customer.address %>
          </div>
        </div>
        
        <div class="row">
          <div class="col-3">
            <p>電話番号</p>
          </div>
          <div class="col-9">
            <%= @customer.telephone_number %>
          </div>
        </div>
  
        <div class="row">
          <div class="col-3">
            <p>メールアドレス</p>
          </div>
          <div class="col-9">
            <%= @customer.email %>
          </div>
        </div>
  
        <div class="row">
          <div class="col-3">
            <p>会員ステータス</p>
          </div>
          <div class="col-9">
            <% if @customer.is_deleted === false %>
              <strong class="text-success">有効</strong>
            <% else %>
            退会
            <% end %>
          </div>
        </div>
  
      </div>
    </div>
  
  <div class="container text-center mt-4">
      <div class="col-xs-offset-1">
        <%= link_to "編集する", edit_admin_customer_path, class: 'btn btn-outline-success' %>
        <%= link_to "注文一覧を見る", admin_products_path, class: 'btn btn-outline-primary' %>
      </div>
  </div>
  
</div>