config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  scope module: :public do
    root to: 'homes#top'
    get "/about"=>"homes#about"
    resources :products, only: [:index, :show]
    resource :customers,only: [] do
      get "my_page"=>"customers#show"
      get "information/edit"=>"customers#edit"
      patch "information"=>"customers#update"
      get "unsubscribe"=>"customers#unsubscribe"
      patch "withdraw"=>"customers#withdraw"
    end

    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete "all_destroy"=>"cart_items#all_destroy"
      end
    end

    resources :orders, only: [:new, :create, :index, :show] do
          collection do
            post "confirm"=>"orders#confirm"
            get "complete"=>"orders#complete"
          end
        end
        resources :delivery_addresses, except: [:new, :show]
      end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
      root to: "homes#top"
      resources :products, except: [:destroy]
      resources :genres, only: [:index, :create, :edit, :update]
      resources :customers, only: [:index, :show, :edit, :update]
      resources :orders, only: [:show, :update] do
        resources :order_details, only: [:update]
      end
    end

  get 'searches/search', to: 'searches#search'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :product
    
    def subtotal
    product.with_tax_price * quantity
    end
    
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    # with_options presence: true do
    #   validates :last_name
    #   validates :first_name
    #   validates :last_name_kana
    #   validates :first_name_kana
    #   validates :email
    #   validates :postal_code
    #   validates :address
    #   validates :telephone_number
    # end

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :delivery_addresses, dependent: :destroy
  
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
  
end

app/models/delivery_address.rb
class DeliveryAddress < ApplicationRecord
    belongs_to :customer



  # private

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + addressee
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
    #t.string :name, null: false
    has_many :products, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
    enum payment_method: { credit_card: 0, transfer: 1 }
    enum order_status: { waiting_for_payment: 0, payment_confirmation: 1, now_at_work: 2, shipping_preparation: 3, sent: 4 }
    belongs_to :customer
    has_many :order_details, dependent: :destroy
    has_many :products ,through: :order_details

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum making_status: { cannot_start: 0, wait_for_production: 1, work_in_progress: 2, production_completed: 3}
    belongs_to :order
    belongs_to :product

    validates :quantity, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :genre

    has_many :carts, dependent: :destroy
    has_many :order_details, dependent: :destroy
    has_many :orders, through: :order_details

    has_one_attached :image

    def with_tax_price
    tax = 1.1
    (tax_excluded_price * tax).floor
    end

    # validation
     validates :name, presence: true
     validates :description, presence: true
     validates :tax_excluded_price,  presence: true

end

app/models/search.rb
class Search < ApplicationRecord
   def self.search(search)
      return Product.all unless search
      Product.where(['content LIKE ?', "%#{search}%"])
    end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render 'index'
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path(@genre.id)
    else
      render "edit"
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
  end

  def update
    order = Order.find(params[:id])
    order.update(order_status_params)

    if order.order_status == Order.order_statuses.key(1)
      order_details = OrderDetail.where(params[:order_id])
        order_details.each do |order_detail|
          order_detail.making_status = OrderDetail.making_statuses.key(1)
          order_detail.save
        end
    end

    redirect_to admin_order_path(order.id)

  end

  private

  def order_status_params
    params.require(:order).permit(:order_status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_admin!, if: -> { request.path =~ /^\/admin/ }
    before_action :authenticate_customer!, if: -> { request.path =~ /^\/customer/ || request.path =~ /^\/cart_items/ || request.path =~ /^\/orders/ || request.path =~ /^\/delivery_addresses/ }

  private
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    #Viewのformで取得したパラメータをモデルに渡す
    @products = Product.search(params[:search])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/serches_helper.rb
module SerchesHelper
end

app/views/admin/genres/edit.html.erb
<h2>ジャンル編集</h2>

<%= form_with model: @genre, url: admin_genre_path(@genre.id) do |f| %>

  <%= f.label :ジャンル名 %>
  <%= f.text_field :name %>

  <%= f.submit "変更を保存", class: "btn btn-success"%>
<% end %>

app/views/admin/genres/index.html.erb
<%= render :layout => '/admin/shared/section_layout', :locals => {:title => 'ジャンル一覧・追加'} do %>
  <div class="card" style="width: 30rem;">
    <div class="card-body">
      <%= form_with model: @genre, url: admin_genres_path do |f| %>
        <%= f.label :ジャンル名 %>&emsp;
        <%= f.text_field :name %>&emsp;
        <%= f.submit "新規登録", class: "btn btn-outline-primary"%>
      <% end %>
    </div>
  </div>
  <table class="table mt-4" style="width: 40%">
    <thead class="thead-lignt bg-light">
      <tr>
        <th>ジャンル</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @genres.each do |genre| %>
        <tr>
          <td><%= genre.name %></td>
          <td><%= link_to '編集する', edit_admin_genre_path(genre.id), class: "btn btn-outline-success" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/admin/orders/show.html.erb
<div class="container my-5 px-5 px-sm-0">
  <div class="row">
    <div class="col">
      <div class="row px-5 py-4">
        <h4 class="bg-light">注文履歴詳細</h4>
      </div>

      <div class="row">
        <div class="col-3">
          <strong>購入者</strong>
        </div>
        <div class="col-9">
          <%= @order.customer.last_name + @order.customer.first_name %><br>
        </div>
      </div>
      <div class="row">
        <div class="col-3">
          <strong>注文日</strong>
        </div>
        <div class="col-9">
          <%= l @order.created_at, format: :short %><br>
        </div>
      </div>
      <div class="row">
        <div class="col-3">
          <strong>配送先</strong>
        </div>
        <div class="col-9">
          <%= '〒' + @order.shipping_postal_code + ' ' +@order.shipping_address %><br>
          <%= @order.shipping_name %>
        </div>
      </div>
      <div class="row">
        <div class="col-3">
          <strong>支払方法</strong>
          </div>
        <div class="col-9">
            <% if @order.payment_method == Order.payment_methods.key(0) %>
              <%= Order.payment_methods_i18n[:credit_card] %>
            <% elsif @order.payment_method == Order.payment_methods.key(1) %>
              <%= Order.payment_methods_i18n[:transfer] %>
            <% end %>
            <br>
          </div>
      </div>

      <%= form_with model: @order, url: admin_order_path(@order.id), method: :patch do |f|%>
        <div class="row">
          <div class="col-3">
            <strong>注文ステータス</strong>
          </div>
          <div class="col-9">
            <%= f.select :order_status, Order.order_statuses.keys.map{|k| [t("enums.order.order_status.#{k}"), k]}%>
            <%= f.submit "更新", class: "btn btn-outline-success"%>
          </div>
        </div>
      <% end %>

        <div class="row">
          <div class="col-9">

        <table class="table">
          <thead class="thead-lignt bg-light">

            <tr>
              <th>商品名</th>
              <th>単価（税込）</th>
              <th>数量</th>
              <th>小計</th>
              <th>制作ステータス</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @order.order_details.each do |order_detail| %>
              <tr>
                <td><%= order_detail.product.name %></td>
                <td><%= order_detail.purchase_price.to_s(:delimited) %></td>
                <td><%= order_detail.quantity %></td>
                <td><%= (order_detail.purchase_price * order_detail.quantity).to_s(:delimited) %></td>
                <%= form_with model: [@order, order_detail], url: admin_order_order_detail_path(@order,order_detail), method: :patch do |f|%>
                  <td><%= f.select :making_status, OrderDetail.making_statuses.keys.map{|k| [t("enums.order_detail.making_status.#{k}"), k]}%></td>
                  <td><%= f.submit "更新", class: "btn btn-outline-success" %></td>
                <% end %>

              </tr>
            <% end %>
          </tbody>
        </table>
        </div>
          <div class="col-2 align-self-end">
            <strong>商品合計</strong><br>
            <strong>送料</strong><br>
            <strong>請求金額合計</strong>
          </div>
          <div class="col-1 text-right align-self-end">
            <%= (@order.total_bill_amount - @order.shipping_fee).to_s(:delimited) + "円" %><br>
            <%= @order.shipping_fee.to_s(:delimited) + "円" %><br>
            <strong><%= @order.total_bill_amount .to_s(:delimited) + "円" %></strong>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>