config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  scope module: :public do
    root to: 'homes#top'
    get "/about"=>"homes#about"
    resources :products, only: [:index, :show]
    resource :customers,only: [] do
      get "my_page"=>"customers#show"
      get "information/edit"=>"customers#edit"
      patch "information"=>"customers#update"
      get "unsubscribe"=>"customers#unsubscribe"
      patch "withdraw"=>"customers#withdraw"
    end

    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete "all_destroy"=>"cart_items#all_destroy"
      end
    end

    resources :orders, only: [:new, :create, :index, :show] do
          collection do
            post "confirm"=>"orders#confirm"
            get "complete"=>"orders#complete"
          end
        end
        resources :delivery_addresses, except: [:new, :show]
      end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
      root to: "homes#top"
      resources :products, except: [:destroy]
      resources :genres, only: [:index, :create, :edit, :update]
      resources :customers, only: [:index, :show, :edit, :update]
      resources :orders, only: [:show, :update] do
        resources :order_details, only: [:update]
      end
    end

  get 'searches/search', to: 'searches#search'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :product
    
    def subtotal
    product.with_tax_price * quantity
    end
    
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    # with_options presence: true do
    #   validates :last_name
    #   validates :first_name
    #   validates :last_name_kana
    #   validates :first_name_kana
    #   validates :email
    #   validates :postal_code
    #   validates :address
    #   validates :telephone_number
    # end

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :delivery_addresses, dependent: :destroy
  
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
  
end

app/models/delivery_address.rb
class DeliveryAddress < ApplicationRecord
    belongs_to :customer



  # private

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + addressee
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
    #t.string :name, null: false
    has_many :products, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
    enum payment_method: { credit_card: 0, transfer: 1 }
    enum order_status: { waiting_for_payment: 0, payment_confirmation: 1, now_at_work: 2, shipping_preparation: 3, sent: 4 }
    belongs_to :customer
    has_many :order_details, dependent: :destroy
    has_many :products ,through: :order_details

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum making_status: { cannot_start: 0, wait_for_production: 1, work_in_progress: 2, production_completed: 3}
    belongs_to :order
    belongs_to :product

    validates :quantity, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :genre

    has_many :carts, dependent: :destroy
    has_many :order_details, dependent: :destroy
    has_many :orders, through: :order_details

    has_one_attached :image

    def with_tax_price
    tax = 1.1
    (tax_excluded_price * tax).floor
    end

    # validation
     validates :name, presence: true
     validates :description, presence: true
     validates :tax_excluded_price,  presence: true

end

app/models/search.rb
class Search < ApplicationRecord
   def self.search(search)
      return Product.all unless search
      Product.where(['content LIKE ?', "%#{search}%"])
    end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render 'index'
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path(@genre.id)
    else
      render "edit"
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  def new
    @product = Product.new
    @genre = Genre.all
    @btn = "新規登録"
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_product_path(@product)
    else
      render :new
    end
  end

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
    @genre = Genre.all
    @btn = "変更を保存"
  end

  def update
     @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_product_path(@product)
    else
      render :edit
    end
  end

  private

  def product_params
    params.require(:product).permit(:image, :genre_id, :name, :description, :tax_excluded_price, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_admin!, if: -> { request.path =~ /^\/admin/ }
    before_action :authenticate_customer!, if: -> { request.path =~ /^\/customer/ || request.path =~ /^\/cart_items/ || request.path =~ /^\/orders/ || request.path =~ /^\/delivery_addresses/ }

  private
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    #Viewのformで取得したパラメータをモデルに渡す
    @products = Product.search(params[:search])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/serches_helper.rb
module SerchesHelper
end

app/views/admin/products/_form.erb
<div class="container my-5 px-5 px-sm-0">

    <%= form_with(model: [ :admin, @product]) do |f| %>
      <div class="form-group row">
        <%= f.label :商品画像, class: 'col-md-3 font-weight-bold'%>
        <%= f.file_field :image, accept: "image/*" %>
      </div>
      <div class="form-group">
        <label for="product_name"><strong>商品名</strong></label>
        <%= f.text_field :name, required: true,class: 'form-control book_title' %>
      </div>
      <div class="form-group">
        <label for="product_discription"><strong>商品説明</strong></label>
        <%= f.text_area :description,required: true, class: 'form-control book_body' %>
      </div>

      <div class="form-group row">
        <%= f.label :ジャンル,required: true, class: 'col-md-3 font-weight-bold' %>
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {prompt: "--選択してください"}, class: "col-md-5 form-control") %>
      </div>

      <div class="form-group row">
          <%= f.label :税抜価格, class: 'col-md-3 font-weight-bold' %>
          <%= f.number_field :tax_excluded_price, required: true,class: 'col-md-5 form-control' %><spna class="col-md-1">円</span>
      </div>

      <div class="form-group row">
        <%= f.label :販売ステータス, class: 'col-md-3 font-weight-bold' %>
        <p class="col-2"><%= f.radio_button :is_active, "true" %>販売中</p>
        <p class="col-2"><%= f.radio_button :is_active, "false" %>販売停止中</p>
      </div>

      <div class="form-group">
        <%= f.submit btn , class: 'btn btn-success' %>
      </div>
    <% end %>

</div>

app/views/admin/products/edit.html.erb
 <div class="row px-5 py-4">
  　<h4 class="bg-light">商品編集</h4>
 </div>
<%= render'admin/products/form', product:@product, genre:@genre, btn:@btn %>

app/views/admin/products/edit.thml.erb
<h4>商品編集</h4>

<%= render'admin/products/form', product:@product, genre:@genre, btn:@btn %>

app/views/admin/products/index.html.erb
<%= render :layout => '/admin/shared/section_layout', :locals => {:title => '商品一覧'} do %>
  <div class="row text-right m-3">
    <%= link_to "+", new_admin_product_path, class: "btn btn-lg rounded-circle text-right bg-light ml-auto shadow-sm" %>
  </div>
  <table class="table">
  <thead class="thead-lignt bg-light">
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= link_to product.name, admin_product_path(product.id) %></td>
        <td><%= product.tax_excluded_price.to_s(:delimited)%></td>
        <td><%= product.genre.name %></td>
        <td>
          <% if product.is_active == true %>
            <p class="text-success font-weight-bold">販売中</p>
          <% else %>
            <p class="text-muted">販売停止中</p>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/admin/products/new.html.erb
<div class="row px-5 py-4 ">
  <h3 class="text-center col col-lg-2 bg-light">商品新規登録</h3>
</div>

<%= render'admin/products/form', product:@product, genre:@genre, btn:@btn %>

app/views/admin/products/show.html.erb
 <div class="row px-5 py-4">
   <h3 class="bg-light">商品詳細</h3>
 </div>

<div class="row">
  <div class="col-md-3 mt-3 text-center">
    <div>
      <% if @product.image.attached? %>
        <%= image_tag @product.image, size: "250x250" %>
      <% else %>
        <%= image_tag 'no_image', size: "250x250" %>
      <% end %>
    </div>
  </div>
    <table class="table table-bordered mt-3 mt-md-0 col-md-8">
      <tbody>
        <tr>
          <td>商品名</td>
          <td><%= @product.name %></td>
        </tr>
        <tr>
          <td>商品説明</td>
          <td><%= @product.description %></td>
        </tr>
        <tr>
          <td>ジャンル</td>
          <td><%= @product.genre.name %></td>
        </tr>
        <tr>
          <td>税込み価格（税抜価格）</htdd>
          <td><%= @product.with_tax_price.to_s(:delimited) %>(<%= @product.tax_excluded_price.to_s(:delimited) %>) 円</span></td>
        </tr>
        <tr>
          <td>販売ステータス</td>
          <td>
            <% if @product.is_active == true %>
              <P class="text-success">販売中
            <% else %>
              販売中止中
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

    <div class="text-center">
      <%= link_to "編集する", edit_admin_product_path(@product), class: "btn btn-success" %>
    </div>
</div>