config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  scope module: :public do
    root to: 'homes#top'
    get "/about"=>"homes#about"
    resources :products, only: [:index, :show]
    resource :customers,only: [] do
      get "my_page"=>"customers#show"
      get "information/edit"=>"customers#edit"
      patch "information"=>"customers#update"
      get "unsubscribe"=>"customers#unsubscribe"
      patch "withdraw"=>"customers#withdraw"
    end

    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete "all_destroy"=>"cart_items#all_destroy"
      end
    end

    resources :orders, only: [:new, :create, :index, :show] do
          collection do
            post "confirm"=>"orders#confirm"
            get "complete"=>"orders#complete"
          end
        end
        resources :delivery_addresses, except: [:new, :show]
      end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
      root to: "homes#top"
      resources :products, except: [:destroy]
      resources :genres, only: [:index, :create, :edit, :update]
      resources :customers, only: [:index, :show, :edit, :update]
      resources :orders, only: [:show, :update] do
        resources :order_details, only: [:update]
      end
    end

  get 'searches/search', to: 'searches#search'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :product
    
    def subtotal
    product.with_tax_price * quantity
    end
    
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    # with_options presence: true do
    #   validates :last_name
    #   validates :first_name
    #   validates :last_name_kana
    #   validates :first_name_kana
    #   validates :email
    #   validates :postal_code
    #   validates :address
    #   validates :telephone_number
    # end

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :delivery_addresses, dependent: :destroy
  
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
  
end

app/models/delivery_address.rb
class DeliveryAddress < ApplicationRecord
    belongs_to :customer



  # private

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + addressee
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
    #t.string :name, null: false
    has_many :products, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
    enum payment_method: { credit_card: 0, transfer: 1 }
    enum order_status: { waiting_for_payment: 0, payment_confirmation: 1, now_at_work: 2, shipping_preparation: 3, sent: 4 }
    belongs_to :customer
    has_many :order_details, dependent: :destroy
    has_many :products ,through: :order_details

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum making_status: { cannot_start: 0, wait_for_production: 1, work_in_progress: 2, production_completed: 3}
    belongs_to :order
    belongs_to :product

    validates :quantity, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :genre

    has_many :carts, dependent: :destroy
    has_many :order_details, dependent: :destroy
    has_many :orders, through: :order_details

    has_one_attached :image

    def with_tax_price
    tax = 1.1
    (tax_excluded_price * tax).floor
    end

    # validation
     validates :name, presence: true
     validates :description, presence: true
     validates :tax_excluded_price,  presence: true

end

app/models/search.rb
class Search < ApplicationRecord
   def self.search(search)
      return Product.all unless search
      Product.where(['content LIKE ?', "%#{search}%"])
    end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_admin!, if: -> { request.path =~ /^\/admin/ }
    before_action :authenticate_customer!, if: -> { request.path =~ /^\/customer/ || request.path =~ /^\/cart_items/ || request.path =~ /^\/orders/ || request.path =~ /^\/delivery_addresses/ }

  private
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    #Viewのformで取得したパラメータをモデルに渡す
    @products = Product.search(params[:search])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/serches_helper.rb
module SerchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/admin/shared/_section_layout.html.erb
<div class="container my-5 px-5 px-sm-0">
    <div class="col">
        <div class="mb-4">
          <h4 class="d-inline bg-light"><%= title %></h4>
        </div>
        <%= yield %>
    </div>
</div>

app/views/layouts/_footer.html.erb
 <footer class="fixed-bottom text-center p-2 bg-light ">
  <div class='container mt-3'>
  	nagano-cake
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light p-4">
    <div class="container-fluid">



       <div><%= link_to image_tag('logo.image.jpg', :size => '50x50'), root_path%></div>
      <!--顧客側ログイン-->
      <% if customer_signed_in? %>
      <span class="navbar-brand mb-0 h1">ようこそ、<%= current_customer.last_name %> さん!</span> <!--まだ名前のリンク入れてないよ。-->
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <li class="mr-2">
            <%= link_to my_page_customers_path, class: 'nav-link text-dark btn btn-outline-secondary me-2' do %>
              マイページ
            <% end %>
          </li>
          <li class="mr-2">
            <%= link_to products_path, class: 'nav-link text-dark btn btn-outline-secondary me-2' do %>
              商品一覧
            <% end %>
          </li>
          <li class="mr-2">
            <%= link_to cart_items_path, class: 'nav-link text-dark btn btn-outline-secondary me-2' do %>
              カート
            <% end %>
          </li>
          <li class="mr-2">
            <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-dark btn btn-outline-secondary me-2' do %>
              ログアウト
            <% end %>
          </li>
        </ul>
        <div>
          <%= render 'layouts/search'%>
        </div>
    </div>

      <!--管理者側ログイン-->
      <% elsif admin_signed_in? %>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <li class="mr-2">
            <%= link_to admin_products_path, class: 'nav-link text-dark btn btn-outline-secondary me-2' do %>
              商品一覧
            <% end %>
          </li>
          <li class="mr-2">
            <%= link_to admin_customers_path, class: 'nav-link text-dark btn btn-outline-secondary me-2' do %>
              会員一覧
            <% end %>
          </li>
          <li class="mr-2">
            <%= link_to admin_root_path, class: 'nav-link text-dark btn btn-outline-secondary me-2' do %>
              注文履歴一覧
            <% end %>
          </li>
          <li class="mr-2">
            <%= link_to admin_genres_path, class: 'nav-link text-dark btn btn-outline-secondary me-2' do %>
              ジャンル一覧
            <% end %>
          </li>
          <li class="mr-2">
            <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-dark btn btn-outline-secondary me-2' do %>
              ログアウト
            <% end %>
          </li>
        </ul>
        <%= render 'layouts/search'%>
      </div>

      <!--顧客・管理者側ログアウト-->
      <% else %>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <li class="mr-2">
            <%= link_to about_path, class: 'nav-link text-dark btn btn-outline-secondary me-2' do %>
              About
            <% end %>
          </li>
          <li class="nav-item mr-2">
            <%= link_to products_path, class: 'nav-link text-dark btn btn-outline-secondary me-2' do %>
              商品一覧
            <% end %>
          </li>
          <li class="mr-2">
            <%= link_to new_customer_registration_path, class: 'nav-link text-dark btn btn-outline-secondary me-2' do %>
              新規登録
            <% end %>
          </li>
          <li class="mr-2">
            <%= link_to new_customer_session_path, class: 'nav-link text-dark btn btn-outline-secondary me-2' do %>
              ログイン
            <% end %>
          </li>
        </ul>
        <%= render 'layouts/search'%>
      </div>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<form>
    <%= form_tag(searches_search_path,:method => 'get') do %>
      <%= text_field_tag :search %>
        <%= submit_tag 'Search', class: "btn btn-outline-success"  %>
    <% end %>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NAGANOCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render'layouts/header' %>

    <main class="mb-auto">
      <%= yield %>
       <div style="height: 100px;" />
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>